### PR TITLE
Bug 1607614: update robustcheckout to latest, hg 5.2 compatible version

### PR DESCRIPTION
**Pull request by cgsheeh**
Updates to the latest robustecheckout, taken from changeset 102106f53cb2
in version-control-tools.

This version includes compatibility with the latest Mercurials,
Py3 support and some new metrics data.

### CODE REVIEW

**Comment by escapewindow** [comment]
@davehouse do we still use build-puppet for relops pools? Do we want to update ronin-puppet robustcheckout in addition/instead?

**Comment by cgsheeh** [comment]
There is a PR for ronin_puppet here: https://github.com/mozilla-platform-ops/ronin_puppet/pull/169

**Comment by davehouse** [comment]
> @davehouse do we still use build-puppet for relops pools? Do we want to update ronin-puppet robustcheckout in addition/instead?

Thanks for checking! We still use build-puppet for linux64 and macos yosemite. (we're planning to move linux64 this year to ronin, and stop/remove yosemite)

**Comment by davehouse** [comment]
I ran this on a test pool and it worked without problems.

**Pull request merged**
