### PR TITLE
only look in /etc/puppet/production for requirements files

### PR DESCRIPTION
**Pull request by escapewindow**

### CODE REVIEW

**Comment by escapewindow** [comment]
[before and after filelists](https://gist.github.com/escapewindow/336b6fd939a9feca1db9f124e6bb68d9)

**Comment by tomprince** [comment]
Does this mean that we'll need to upload files manually, if we want to test new dependencies out?

**Comment by escapewindow** [comment]
That's correct. No automatic downloads for user envs.

**Comment by tomprince** [comment]
Rather than not downloading for user env's, could we instead email just that user, if there is a failure in their env?

**Comment by escapewindow** [comment]
That's possible, but will take a larger patch.

**Pull request merged**
